name: Test Orchestrator Action locally with Act

on:
  push:
    branches: [ "main" ]

jobs:
  test-orchestrator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Docker Compose Orchestrator
        uses: cmsong111/docker-compose-orchestrator@v0.0.4
        with:
          volume-path: './database/volume.yaml'
          network-path: './database/network.yaml'
